export const GET_COURSE_DATA = 'GET_COURSE_DATA';
export const GET_STUDENT_DATA = 'GET_STUDENT_DATA';
export const GET_SCHEDULED_DATA = 'GET_SCHEDULED_DATA';
export const GET_COURSE_NO_COUNT = 'GET_COURSE_NO_COUNT';
// export const GET_USER_DETAILS = 'GET_USER_DETAILS';


